curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is the capital of Australia?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "When did the First World War begin?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "Who was Albert Einstein?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is the speed of light?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is blockchain technology?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What are the largest deserts in the world?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "Who wrote the play Hamlet?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is photosynthesis?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is the Pythagorean theorem?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "Who won the FIFA World Cup in 2018?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is a black hole?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "Who was the first President of the United States?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is inflation?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "Who composed the Symphony No. 9?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is Impressionism?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is the function of the liver?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is existentialism?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is democracy?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is artificial intelligence?"}]}'
curl -X POST http://localhost:8080/generate -H "Content-Type: application/json" -d '{"messages": [{"role": "user", "content": "What is climate change?"}]}'